            <!-- <h2><?php// print_r($data) ?></h2> -->
                           <!-- content -->
                           <div class="card">
                                <div class="card-body">
                    
                                    <h4 class="card-title">Add New Result For a New Polling Unit</h4>
                                    
                                    
                                    <form method="post"  class="form-submit" id="newStudentForm" enctype="multipart/form-data">

                                        <div class="form-group mb-3">
                                                <label for="pollunit" class="col-3 col-form-label">Select Polling Unit </label>
                                                <div class="col-12">
                                                <select class="form-control" name="pollunit" id="pollunit" required>
                                                <?php 
                                                        $cnt1=1; $results1=$data[0];
                                                        if($results1 <> "" && $results1 <> 1): foreach($results1 as $result1):   ?>
                                                    <option value="<?php echo $result1->uniqueid ; ?>"> <?php echo $result1->polling_unit_number ; ?> - <?php echo $result1->polling_unit_name ; ?></option>
                                                <?php $cnt1++; endforeach; endif; ?>
                                                </select>
                                                </div>
                                        </div>

                                        <div class="form-group mb-3">
                                                <label for="party" class="col-3 col-form-label">Select Party </label>
                                                <div class="col-12">
                                                <select class="form-control" name="party" id="party" required>
                                                <?php 
                                                        $cnt2=1; $results2=$data[1];
                                                        if($results2 <> "" && $results2 <> 1): foreach($results2 as $result2):   ?>
                                                    <option value="<?php echo $result2->partyid ; ?>">  <?php echo $result2->partyname ; ?></option>
                                                <?php $cnt2++; endforeach; endif; ?>
                                                </select>
                                                </div>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="score" class="col-3 col-form-label">Enter Score</label>
                                            <div class="col-12">
                                                <input type="number" class="form-control" name="score" placeholder="Enter Polling Unit Score" required>
                                            </div>
                                        </div>

                                        <div class="form-group mb-3">
                                            <label for="agent" class="col-3 col-form-label">Enter By (supposed to be generated by default )</label>
                                            <div class="col-12">
                                                <input type="text" class="form-control" name="agent" placeholder="Enter Your Name" required>
                                            </div>
                                        </div>
                                      
                                        <div class="form-group mb-0 ">
                                            <div class="col-12">
                                                <button type="submit" name="add-new-result" class="btn btn-info waves-effect waves-light submit-btn"><i class="fa fa-plus"></i> Add New Result</button>
                                            </div>
                                        </div>
                                    </form>
                                </div> <!-- end card-body-->
                            </div> <!-- end card-->
